name = "medizoserver"
account_id = "2f740823719b4ab11c6b134a71e7a3b9"
main = "worker.mjs"
compatibility_date = "2026-08-12"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "medizolifecloud"
database_id = "206ec373-b5bb-4ec4-8304-778692299181"

[vars]
CLIENT_URL = "https://medizo.life"
CLOUDFLARE_ACCOUNT_ID = "2f740823719b4ab11c6b134a71e7a3b9"
CLOUDFLARE_D1_DATABASE_ID = "206ec373-b5bb-4ec4-8304-778692299181"
DIGILOCKER_CLIENT_ID = "MK0F1D807D"
DIGILOCKER_REDIRECT_URI = "https://api.medizo.life/api/digilocker/callback"
DIGILOCKER_BASE_URL = "https://digilocker.meripehchaan.gov.in"
# JWT_SECRET and DIGILOCKER_CLIENT_SECRET are set as encrypted wrangler secrets
